### ISSUE TITLE
Replace dd with fio? 

### ISSUE THREAD

**Issue by Daniel15** [masonr/yet-another-bench-script#1]
`dd` isn't a good benchmarking tool. It only tests sequential writes which are not very common in real-world applications. Additionally, its results can be affected by caching on the host (which is impossible to bypass on a VPS). 

See:
https://support.binarylane.com.au/support/solutions/articles/1000055889-how-to-benchmark-disk-i-o
https://unix.stackexchange.com/a/150681

A better option would be to use fio and test both random reads and writes. ServerScope runs a bunch of fio tests, as an example.

**Comment by masonr** [comment]
I agree that dd (and ioping for that matter) are both inadequate measures of disk performance. I did try to get fio working with this, however it'll either require elevated privileges (to install fio) or the user to install prerequisites (building fio from source), both of which I'm trying to avoid for this script.

As an alternative, I'm considering baking in something that will detect if fio is installed and available on the user's system and use that in place of dd/ioping, if detected. This will get around both requirements (elevated privileges and installed prereqs), but can still use a more accurate disk performance test if the user has fio installed.

**Comment by Daniel15** [comment]
> I'm considering baking in something that will detect if fio is installed and available on the user's system and use that in place of dd/ioping, if detected

This is a good idea. I wouldn't even use dd as a fallback; I'd just print out an error message like "cannot do disk I/O speed test unless fio is installed"

What about building a statically-linked version of fio and downloading it in the script? That might work too.

**Comment by masonr** [comment]
> What about building a statically-linked version of fio and downloading it in the script? That might work too.

If I can get it to compile and work on other machines, I'll definitely do that since it's the same approach I'm taking with ioping. The couple attempts I made at this resulted in the compiled binary not working correctly on other machines (some it did, some it didn't). I'll take another stab at it soon and see if I can get it to compile and to run on other machines without any issues. I'll likely have to compile a 32-bit and a 64-bit version, but that's fine.

**Comment by masonr** [comment]
fio implemented within 5ba34f9

**Comment by Daniel15** [comment]
Thank you @masonr! This is great :D
