### ISSUE TITLE
curl -sL yabs.sh | bash -s -- -{fdighr4} returns illegal option

### ISSUE THREAD

**Issue by changchichung** [masonr/yet-another-bench-script#16]
OS: ubuntu 18.04 / ubuntu 20.04

```
2020-11-24 11:08:26 [cch@dc034 ~]$ curl -sL yabs.sh | bash -s -- -{fdighr4}
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2020-11-20                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Tue Nov 24 11:08:31 CST 2020
bash: illegal option -- {
2020-11-24 11:08:31 [cch@dc034 ~]$ 
```

**Comment by masonr** [comment]
The options in the curly braces -- { } -- are all of the available ones. Leave out the curly braces and choose and pick which ones you need for your test when issuing the curl command.

E.g.
`curl -sL yabs.sh | bash -s -- -dg`
The above runs _only_ the iperf/network tests ( -d disables disk test, -g disables geekbench test.

`curl -sL yabs.sh | bash`
To run the default setup (all three tests), use the above.

Hope this helps!
