### ISSUE TITLE
Latency check

### ISSUE THREAD

**Issue by StoreHost** [masonr/yet-another-bench-script#2]
It may would be nice to also check the latency for the network speed test.

**Comment by masonr** [comment]
If I can think of a way to incorporate this that won't blow out the table even more, I will. At the moment, I don't really want to tack on any extra character into the network table as it's already pretty large. Maybe I'll have the latency times print to their own table or something. Will think about this.

**Comment by masonr** [comment]
Putting this to rest for now. No plans to implement currently. Will reopen/reference if it's visited again in the future.
