### ISSUE TITLE
Change Indonesia's iperf test server

### ISSUE THREAD

**Issue by nirvash21** [masonr/yet-another-bench-script#29]
Hi, can you change Indonesia's iperf server location to different one? Since it mostly appears "busy". Probably not functioning anymore?

Thanks,

**Comment by masonr** [comment]
Resolved in 6af7852

Will update, if/when I find a good replacement.

**Comment by 3xploiton3** [comment]
please add indonesia server again,

https://iperf.fr/iperf-servers.php
