### ISSUE TITLE
Speedtest will not be executed

### ISSUE THREAD

**Issue by freaky33** [masonr/yet-another-bench-script#31]
I'm using Debian 10.
When running the script without any flags with either of the two commands the script doesn't do any speedtests.
It does not show an error.

It will just print out the fio results and after that the geekbench results.

**Comment by masonr** [comment]
Can you paste the full output so I can better diagnose what's going on? Also post the output of just running the -h flag (`curl -sL yabs.sh | bash -s -- -h`) as that may have some info that helps identify the cause.

**Comment by freaky33** [comment]
Normal Output:
`# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2021-12-03                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Mon 20 Dec 2021 07:47:55 PM CET

Basic System Information:
---------------------------------
Processor  : AMD EPYC 7702P 64-Core Processor
CPU cores  : 4 @ 1996.248 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ❌ Disabled
RAM        : 15.7 GiB
Swap       : 0.0 KiB
Disk       : 157.4 GiB

fio Disk Speed Tests (Mixed R/W 50/50):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 40.25 MB/s   (10.0k) | 399.62 MB/s   (6.2k)
Write      | 40.34 MB/s   (10.0k) | 401.73 MB/s   (6.2k)
Total      | 80.59 MB/s   (20.1k) | 801.35 MB/s  (12.5k)
           |                      |
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 810.66 MB/s   (1.5k) | 1.04 GB/s     (1.0k)
Write      | 853.73 MB/s   (1.6k) | 1.11 GB/s     (1.0k)
Total      | 1.66 GB/s     (3.2k) | 2.15 GB/s     (2.1k)

Geekbench 5 Benchmark Test:
---------------------------------
Test            | Value
                |
Single Core     | 831
Multi Core      | 3028
Full Test       | https://browser.geekbench.com/v5/cpu/11717484
`

Running `curl -sL yabs.sh | bash -s -- -h` does not give me an output at all.

**Comment by masonr** [comment]
Output is strange, it should be printing an error if it's unable to perform the iperf test but seems like it's skipping it instead for whatever reason. Will have to dig more into the code to see what may cause this. To confirm -- you just run "curl -sL yabs.sh | bash" to produce your first output, correct?

Also seems like it's not detecting connectivity successfully. What's the output of these commands?

```
ping -4 -c 1 -W 4 ipv4.google.com
curl -4 -m 4 icanhazip.com
```

```
ping -6 -c 1 -W 4 ipv6.google.com
curl -6 -m 4 icanhazip.com
```

Feel free to redact your IP address from the output, no need to post that publicly.

**Comment by freaky33** [comment]
I'm sorry for wasting your time. Some installed application changed the DNS Server to something completely off.
Changed it back and it's working now. Thank you.

**Comment by masonr** [comment]
@freaky33 - no worries! Glad you were able to find the fix. I'm going to add a check to the script that if IPv4 and IPv6 connectivity are both not detected, then it'll warn the user to check their DNS config. I don't think this is the first time something like this has happened if memory serves me right.
