### ISSUE TITLE
Geekbench not uploading results.

### ISSUE THREAD

**Issue by uwuplant** [masonr/yet-another-bench-script#36]
Ran yabs on my PC to test it, and noticed that the script just hangs after Geekbench finishes running. All other tests run fine, but the script never finishes running.

![image](https://user-images.githubusercontent.com/26153075/162349077-f90589d9-94b5-40ec-91c7-18ad3181d3d8.png)

Glad to provide any more information if needed.

**Comment by masonr** [comment]
What does the output look like when running outside of the script?

```
curl https://cdn.geekbench.com/Geekbench-5.4.4-Linux.tar.gz | tar xz --strip-components=1
./geekbench5 --upload
```

**Comment by uwuplant** [comment]
![Screenshot_20220408-002627_JuiceSSH](https://user-images.githubusercontent.com/26153075/162363614-f6fdb377-08c5-4d78-89d9-4ce25aa84d44.jpg)

**Comment by uwuplant** [comment]
oops, phone moment.

**Comment by masonr** [comment]
Judging by where your cursor currently is in the screenshot, it looks like after the geekbench test was done, it just stays there and doesn't exit out of the geekbench program. Is that correct (i.e. did you have to ctrl+c to return to shell)?

If that's the case, then it's a geekbench issue. Could open a thread on the GB support forum, but I'm not really sure what would be causing this as it's outside of the scope of YABS.

**Comment by uwuplant** [comment]
I did have to, will report it there then. Thank you!
