### ISSUE TITLE
Geekbench 5 fail causes corrupt JSON

### ISSUE THREAD

**Issue by cp6** [masonr/yet-another-bench-script#41]
When the Geekbench 5 test fails (not enough ram) 

> Geekbench 5 test failed. Run manually to determine cause.

The JSON becomes corrupted at the geekbench section:

`,"geekbench":]`

instead of being

`,"geekbench":[]`

The output

`{"version":"v2022-08-20","time":"20220827-073833","os":{"arch":"x64","distro":"Ubuntu 22.04 LTS","kernel":"5.15.0-1004-kvm","uptime":1876106.72},"net":{"ipv4":true,"ipv6":true},"cpu":{"model":"Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz","cores":1,"freq":"2899.996 MHz","aes":true,"virt":false},"mem":{"ram":1008484,"swap":0,"disk":9617654},"fio":[{"bs":"4k","speed_r":109145,"iops_r":27286,"speed_w":109433,"iops_w":27358,"speed_rw":218578,"iops_rw":54644},{"bs":"64k","speed_r":219411,"iops_r":3428,"speed_w":220566,"iops_w":3446,"speed_rw":439977,"iops_rw":6874},{"bs":"512k","speed_r":235707,"iops_r":460,"speed_w":248231,"iops_w":484,"speed_rw":483938,"iops_rw":944},{"bs":"1m","speed_r":239053,"iops_r":233,"speed_w":254974,"iops_w":248,"speed_rw":494027,"iops_rw":481}],"iperf":[{"mode":"IPv4","provider":"Clouvider","loc":"London, UK (10G)","send":"1.02 Gbits/sec","recv":"1.37 Gbits/sec"},{"mode":"IPv4","provider":"Online.net","loc":"Paris, FR (10G)","send":"658 Mbits/sec","recv":"1.16 Gbits/sec"},{"mode":"IPv4","provider":"Clouvider","loc":"NYC, NY, US (10G)","send":"1.98 Gbits/sec","recv":"2.25 Gbits/sec"},{"mode":"IPv6","provider":"Clouvider","loc":"London, UK (10G)","send":"1.30 Gbits/sec","recv":"1.45 Gbits/sec"},{"mode":"IPv6","provider":"Online.net","loc":"Paris, FR (10G)","send":"1.61 Gbits/sec","recv":"1.34 Gbits/sec"},{"mode":"IPv6","provider":"Clouvider","loc":"NYC, NY, US (10G)","send":"3.25 Gbits/sec","recv":"3.19 Gbits/sec"}],"geekbench":]}`

**Comment by masonr** [comment]
Good catch! I'll get that patched up soon.

Thanks!

**Comment by masonr** [comment]
Just patched this up, sorry it took so long!
