### ISSUE TITLE
iperf3 always busy ?

### ISSUE THREAD

**Issue by 3xploiton3** [masonr/yet-another-bench-script#47]
https://i.imgur.com/D18zZrd.png

why iperf3 speed test on my VPS always busy?

**Comment by masonr** [comment]
This is normally a result of your OS not being compatible with the iperf3 binary that is downloaded from this repo. Depending on your OS, I'd recommend downloading/installing iperf3 natively on your machine. Also, ensure that this iperf3 package works as expected. YABS will then detect that a locally installed version of iperf3 is installed an use that instead for the test. Reopen/reply to this issue if you experience any other problems after taking these steps.
