### ISSUE TITLE
Additional fio block sizes

### ISSUE THREAD

**Issue by camjac251** [masonr/yet-another-bench-script#5]
Would it be possible to test further block sizes for those with SSDs? I was curious to see how 1GB or 512M would bench since I'm on an NVME drive.

**Comment by masonr** [comment]
Thanks for the suggestion. I'll look into this a bit and do some testing to see if it'll be beneficial. Most likely would be implemented as a flag if I decide to bake it in. I've been wanting to clean up the disk test code anyway, so this might give me a good opportunity to do so.

**Comment by camjac251** [comment]
Is there any chance that the tests done after 4kb are cached in any way? If I test this script vs bench.sh or MonkeyTest, I don't see as fast of a speed with the others as I do with fio.

**Comment by masonr** [comment]
No, fio doesn't cache results and does non-cached random writes/reads for every test. I'm not familiar with MonkeyTest, but bench.sh does sequential disk speeds which are often way different than random read/write tests. SSDs/NVMe drives often do rather poorly on sequential tests and very well on more real-world tests (random read/writes).

**Comment by masonr** [comment]
@camjac251 so after testing this on and off the past couple months, I haven't really seen any instances where using higher block sizes than the highest default size (1mb) results in any significant speed boost, either on nvme, ssd, or spinning rust drives. So with that I'm not sure it's worth adding an option into the script to use higher block sizes as it won't really be beneficial for most people.

Have you tried testing with the fio utility yourself to see if you see any significant difference in throughput when doing really large block sizes? I'm curious what behavior you're seeing with large block sizes like that.

**Comment by masonr** [comment]
Closing pending further discussion.
