### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by mrkaffeine92** [masonr/yet-another-bench-script#52]
I ran this command on 4 of my VPS's and one of them did not return any info.

I run the command and it shows it starting with Date but that's it.

Any ideas?

**Comment by masonr** [comment]
Need some more info. What's the output look like when you run the command (copy/past or screenshot here)? What's the exact command you are running? 

Please run this command, which uses the -h (help) flag and will just print some info and exit without running any tests, paste the results here.

**Comment by mrkaffeine92** [comment]
Hello, I had to reconfigure the server and re-install the distro but it ended up working after a few tries.

I was wondering if you had a more AIO script that I can run on a few VPS Servers and it'll spit out a % or let me know if it's Good, very Good etc rating.

Thank you,

------- Original Message -------

**Comment by mrkaffeine92** [comment]
It does not run Gb5 test. Here is log running -h flag:

# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2022-12-04                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Fri 23 Dec 2022 04:33:16 PM UTC

Usage: ./yabs.sh [-flags]
       curl -sL yabs.sh | bash
       curl -sL yabs.sh | bash -s -- -flags
       wget -qO- yabs.sh | bash
       wget -qO- yabs.sh | bash -s -- -flags

Flags:
       -b : prefer pre-compiled binaries from repo over local packages
       -f/d : skips the fio disk benchmark test
       -i : skips the iperf network test
       -g : skips the geekbench performance test
       -h : prints this lovely message, shows any flags you passed,
            shows if fio/iperf3 local packages have been detected,
            then exits
       -r : reduce number of iperf3 network locations (to only three)
            to lessen bandwidth usage
       -4 : use geekbench 4 instead of geekbench 5
       -9 : use both geekbench 4 AND geekbench 5
       -j : print jsonified YABS results at conclusion of test
       -w <filename> : write jsonified YABS results to disk using file name provided
       -s <url> : send jsonified YABS results to URL

Detected Arch: x64

Detected Flags:
       running geekbench 5

Local Binary Check:
       fio not detected, will download precompiled binary
       fio detected, using local package
       iperf3 not detected, will download precompiled binary
       iperf3 detected, using local package

Detected Connectivity:
       IPv4 connected
       IPv6 not connected

JSON Options:
       none

Exiting...

**Comment by masonr** [comment]
> I was wondering if you had a more AIO script that I can run on a few VPS Servers and it'll spit out a % or let me know if it's Good, very Good etc rating.

I do not. A "scoring" system was intentionally left out since it would have been very subjective since people have different requirements. You can compare geekbench scores on the geekbench site itself to see what other machines are scoring with different specs. There are also a few different websites that have some YABS scores uploaded for comparison and displaying test results, which may be useful.

> It does not run Gb5 test

Most common cause of this is that your machine does not have enough memory. If your machine has <2GB of RAM, then you'll most likely need at least 0.5GB of swap space, alternatively you could also try to run the GB4 test instead which seems to run fine on low-memory machines (use the -4 flag). Could also get more clues as to why it's not running by downloading the GB5 files and running the program manually so you can see any error messages.

**Comment by mrkaffeine92** [comment]
Hello,
Thank you for response. The VPS is a Ryzen with 2 Core and 2GB memory.
Can you please briefly explain how to download Gb5 file and run manually?

Thank you

------- Original Message -------

**Comment by masonr** [comment]
Okay, it _should_ run fine on a machine like that. Here's how to run manually --

```
mkdir gb5
curl https://cdn.geekbench.com/Geekbench-5.4.5-Linux.tar.gz | tar xz --strip-components=1 -C gb5
cd gb5/
./geekbench5
```

As it runs it'll print which test are being executed. Search any error messages that pop up to see what the common causes of them are. After it's done, you can clean up the gb5 files if you want with: `rm -r gb5`.

**Comment by mrkaffeine92** [comment]
It is 1GB RAM / Core* sorry.
Here is the log, I don't see any test results, MultiCore Test or any errors LOL:

***@***.***:~/gb5# ./geekbench5
Geekbench 5.4.5 Tryout : https://www.geekbench.com/

Geekbench 5 requires an active Internet connection when in tryout mode and
automatically uploads benchmark results to the Geekbench Browser.

Buy a Geekbench 5 license from the Primate Labs Store to enable offline use
and unlock other features:

https://store.primatelabs.com/v5

Enter your Geekbench 5 license using the following command line:

./geekbench5 --unlock <email> <key>

Running Gathering system information
System Information
Operating System Ubuntu 20.04.5 LTS
Kernel Linux 5.4.0-105-generic x86_64
Model Red Hat KVM
Motherboard N/A
BIOS SeaBIOS 1.15.0-2.module_el8.6.0+2880+7d9e3703

Processor Information
Name AMD Ryzen 9 5900X
Topology 1 Processor, 1 Core
Identifier AuthenticAMD Family 25 Model 33 Stepping 2
Base Frequency 3.69 GHz
L1 Instruction Cache 64.0 KB
L1 Data Cache 64.0 KB
L2 Cache 512 KB
L3 Cache 16.0 MB

Memory Information
Size 977 MB

Single-Core
Running AES-XTS
Running Text Compression
Running Image Compression
Running Navigation
Running HTML5
Running SQLite
Running PDF Rendering
Running Text Rendering
Running Clang
Running Camera
Running N-Body Physics
Running Rigid Body Physics
Running Gaussian Blur
***@***.***:
------- Original Message -------

**Comment by masonr** [comment]
If it's getting cut off like that without any errors, then it's likely a monitor on the host node that is killing the process. Some hosts limit the CPU a VM is permitted to use. May be worth reaching out to your host's support to get clarification on the CPU usage policy, but that's up to you. Ultimately this doesn't appear to be a YABS-related issue.

**Comment by mrkaffeine92** [comment]
Hello,
Thank you for taking a look and clarifying.
I will reach out!

Merry Christmas,
------- Original Message -------

**Comment by masonr** [comment]
No problem at all.

Thank you and Merry Christmas to you too!

Cheers!
