### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sugarlesss** [masonr/yet-another-bench-script#55]
When I run yab.sh on CentOS 7.9, I encounter the following error.
```
[root@dbis ~]# bash yabs.sh 
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2022-12-04                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Sun Jan  1 23:55:11 CST 2023

Basic System Information:
---------------------------------
Uptime     : 20 days, 10 hours, 16 minutes
Processor  : Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
CPU cores  : 2 @ 3000.003 MHz
AES-NI     : ? Enabled
VM-x/AMD-V : ? Disabled
RAM        : 4.9 GiB
Swap       : 2.0 GiB
Disk       : 67.1 GiB
Distro     : CentOS Linux 7 (Core)
Kernel     : 3.10.0-957.el7.x86_64

Generating fio test file...yabs.sh: line 355: 124589 Segmentation fault      (core dumped) $FIO_CMD --name=setup --ioengine=libaio --rw=read --bs=64k --iodepth=64 --numjobs=2 --size=$FIO_SIZE --runtime=1 --gtod_reduce=1 --filename=$DISK_PATH/test.fio --direct=1 --minimal &>/dev/null
fio Disk Speed Tests (Mixed R/W 50/50):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       |                   () |                   ()
Write      |                   () |                   ()
Total      | 0.00 KB/s        (0) | 0.00 KB/s        (0)
           |                      |                     
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       |                   () |                   ()
Write      |                   () |                   ()
Total      | 0.00 KB/s        (0) | 0.00 KB/s        (0)

iperf3 binary download failed. Skipping iperf network tests...

Running GB5 benchmark test... *cue elevator music*^C
** Aborting YABS. Cleaning up files...
```

After testing, I found that the problem is with fio_x64
```
[root@abc ~]# ./fio_x64 -v
Segmentation fault (core dumped)
```

I looked at the error message in the corefile and it reads as follows.
```
[root@dbis ~]# gdb corefile core.125789
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
corefile: No such file or directory.
[New LWP 125789]
Core was generated by `./fio_x64 -v'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000040641a in ?? ()
(gdb)
```

But it's so strange that I don't encounter similar problems when using fio_x64 directly on other CentOS 7.9.

I have absolutely no clue.

**Comment by molixiaoge** [comment]
Same problem with Ubuntu 22.04.2 LTS
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2024-06-09                    #
# https://github.com/masonr/yet-another-bench-script #





Generating fio test file..../yabs.sh: line 426: 1130610 Segmentation fault      $FIO_CMD --name=setup --ioengine=libaio --rw=read --bs=64k --iodepth=64 --numjobs=2 --size=$FIO_SIZE --runtime=1 --gtod_reduce=1 --filename="$DISK_PATH/test.fio" --direct=1 --minimal &> /dev/null
fio Disk Speed Tests (Mixed R/W 50/50) (Partition /dev/vda1):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       |                   () |                   ()
Write      |                   () |                   ()
Total      | 0.00 KB/s        (0) | 0.00 KB/s        (0)
           |                      |                     
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       |                   () |                   ()
Write      |                   () |                   ()
Total      | 0.00 KB/s        (0) | 0.00 KB/s        (0)
