### ISSUE TITLE
Geekbench 6 is released now, wish to add support to v6

### ISSUE THREAD

**Issue by Debcharon** [masonr/yet-another-bench-script#58]
Noticed that Geekbench (v6) is out recently, view on [Geekbench blog](https://www.geekbench.com/blog/2023/02/geekbench-6/).

When to support or compatible with v6, thanks.

**Comment by masonr** [comment]
Geekbench 6 has been added to the script as the default test in 06eaa2a with backwards compatibility with GB4 and GB5.
