### ISSUE TITLE
YABS always freezes at the same time

### ISSUE THREAD

**Issue by pReya** [masonr/yet-another-bench-script#63]
Hey, I'm trying to run YABS on a brand new VPS with Debian 11. However, my SSH session always freezes around the same time. I don't know how to debug this. Can I somehow find out, if YABS crashed, or if it's "just" the SSH session that breaks?

The problem is, after this happens, I can't even log back into the machine via SSH. I'm just getting SSH timeouts. It seems that YABS crashes/blocks the server completely. However in my Hoster control panel I can see that the server CPU/RAM are not maxed out at all – they seem to be idling. I assume I'm hitting some kind of "SSH cooldown period" or something, because I can't reach the server even after restarting it.

Here's the output until the point where it freezes:

```
➜  ~ curl -sL yabs.sh | bash
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2023-03-24                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Wed Apr  5 09:02:23 CEST 2023

Basic System Information:
---------------------------------
Uptime     : 0 days, 9 hours, 19 minutes
Processor  : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
CPU cores  : 8 @ 2899.932 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ✔ Enabled
RAM        : 32.0 GiB
Swap       : 1.0 GiB
Disk       : 984.2 GiB
Distro     : Debian GNU/Linux 11 (bullseye)
Kernel     : 4.19.0
VM Type    : OPENVZ
Net Online : IPv4

IPv4 Network Information:
---------------------------------
ISP        : dogado GmbH
ASN        : AS45012 dogado GmbH
Host       : Providerbox
Location   : Leipzig, Saxony (SN)
Country    : Germany

fio Disk Speed Tests (Mixed R/W 50/50):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 2.57 MB/s      (643) | 38.77 MB/s     (605)
Write      | 2.59 MB/s      (648) | 39.08 MB/s     (610)
Total      | 5.16 MB/s     (1.2k) | 77.86 MB/s    (1.2k)
           |                      |
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 79.03 MB/s     (154) | 37.04 MB/s      (36)
Write      | 83.23 MB/s     (162) | 40.41 MB/s      (39)
Total      | 162.27 MB/s    (316) | 77.45 MB/s      (75)

iperf3 Network Speed Tests (IPv4):
---------------------------------
Provider        | Location (Link)           | Send Speed      | Recv Speed      | Ping
-----           | -----                     | ----            | ----            | ----
Clouvider       | London, UK (10G)          | 381 Mbits/sec   | 8.82 Gbits/sec  | 17.7 ms
Scaleway        | Paris, FR (10G)           | 381 Mbits/sec   | 6.66 Gbits/sec  | 25.1 ms
NovoServe       | North Holland, NL (40G)   | 384 Mbits/sec   | 8.39 Gbits/sec  | 15.8 ms
Uztelecom       | Tashkent, UZ (10G)        | 367 Mbits/sec   | 3.56 Gbits/sec  | 85.8 ms
Performing IPv4 iperf3 send test to Clouvider (Attempt #3 of 3)...
```

**Comment by insign** [comment]
To me always freeze ate geekbench test, so I downloaded and ran manually

**Comment by masonr** [comment]
This sounds like something on the host/provider's end that is kicking in and freezing your VM for a cool down period. I think it is likely that based on the "freeze" occurring during the network test portion and being unable to even SSH into the VM when this happens. Due to the nature of the speed test, where it quite literally attempts to maximize the throughput, it is not uncommon for anti-DDoS systems and/or network anti-abuse scripts to be triggered and null route your IP for a period of time.

I'd suggest raising a ticket with the host of your machine to see if you are hitting any limits resulting in the network being switched off for a short time.

**Comment by masonr** [comment]
Closing pending any status updates.
