### ISSUE TITLE
GeekBench 6 is unsupported on CentOS 7

### ISSUE THREAD

**Issue by diamondzxd** [masonr/yet-another-bench-script#71]
Found out after diving into the issue why does GB test fails on Centos 7 machines. The same would be the case for similar older distros.

Upon running geekbench 6 manually, the following output is seen : 

```./geekbench_x86_64: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./geekbench_x86_64)```

This is because CentOS 7 ships with `glibc 2.17-326.el7_9`, however, minimum 2.27 version is required to execute.

The similar issues are observed when trying to install latest nodejs versions which are built on newer libc versions.
Ref : 
- https://github.com/pyg-team/pytorch_geometric/issues/3593
- https://saturncloud.io/blog/how-to-solve-the-glibc227-not-found-error-while-installing-node-on-amazon-ec2-instance/
- https://bobbyhadz.com/blog/node-glibc-not-found-required-by-node

The same issues were reported in some Amazon Linux AMI's as well.

The intent of making this issue is to make aware and possibly update the support of YABS, or include a check and displaying that `this distro is close to EOL, please consider upgrading to a newer distro` or alternatively use alternate GB5 or GB4 for those instances.

**Comment by masonr** [comment]
Really appreciate the bug report! Never knew CentOS 7 had issues running the geekbench binary before. I'll investigate and see what I can come up with -- ideally I'd like the script use a workaround to get GB running (looks like I may be able to download a later glibc and use LD_PRELOAD when running GB) or like you said ill simply detect the issue beforehand and display an error message/link to a workaround.

**Comment by diamondzxd** [comment]
Thanks for confirming! Both the ideas seem doable, let me know if you want a PR for this, would love to contribute!

**Comment by masonr** [comment]
Warning message added in eb80002. Decided not to download and preload an alternative glibc as that opens the door to additional incompatibility and security challenges. Warning message is sufficient for now.
