### ISSUE TITLE
define a custom location for the fio test

### ISSUE THREAD

**Issue by nmcc1212** [masonr/yet-another-bench-script#73]
for example i have a pool mounted on /mnt/pool how would i set the fio test to run there

(Briefly) looking at the script i saw the variable $disk_path used, but could not figure out where it was being defined

**Comment by masonr** [comment]
Hey there -- the test will use the current directory's disk for the fio test. So to run the fio test on your mounted disk, just `cd` into it before calling YABS. I'm working on documentation now, so I'll make sure this explanation is included somewhere as I get asked this question quite frequently.

**Comment by nmcc1212** [comment]
Thanks!
