### ISSUE TITLE
Invalid backslash in uploaded json

### ISSUE THREAD

**Issue by plerohellec** [masonr/yet-another-bench-script#80]
I'm receiving invalid yabs.sh json payloads almost daily at vpsbenchmarks.com. They are invalid because one or more strings in the json include a backslash that is not used as an escape character. It looks like the \ is escaping a double quote but it was not meant to. For example:
"asn":"AS44486 Oliver Horscht is trading as \SYNLINQ\\"
or
"isp":"OOO \Network of data-centers \Selectel\\"

Would it be possible to escape or delete those backslashes before including them in the json strings?

Here is an example with the full json input:
[yab.invalid-backslash.json](https://github.com/masonr/yet-another-bench-script/files/13507025/yab.invalid-backslash.json)

**Comment by masonr** [comment]
Appreciate the bug report! Should be easy to filter out the backslashes. Has the network details section been the only area you have been receiving backslashes? I don't think any other field would be susceptible to bad input, but I want to confirm before implementing a change.

**Comment by plerohellec** [comment]
Yes, I've only seen it in the isp and asn fields but I assume all of the ip_info section is susceptible of including those backslashes. I suppose the backslash could also be found in cpu models since VPS providers can set it any way they want.
Thanks for taking the time to fix this!

**Comment by plerohellec** [comment]
I just realized that ip-api.com returns json like this in those cases:
```json
{
    "as": "AS44486 Oliver Horscht is trading as \"SYNLINQ\"",
    "city": "Frankfurt am Main",
    "country": "Germany",
    "countryCode": "DE",
    "isp": "Oliver Horscht is trading as \"SYNLINQ\"",
    "lat": 50.1109,
    "lon": 8.68213,
    "org": "Solutions Virfect",
    "query": "103.252.88.1",
    "region": "HE",
    "regionName": "Hesse",
    "status": "success",
    "timezone": "Europe/Berlin",
    "zip": "60313"
}
```
So yabs.sh must be removing the " but keeping the \\. It should either keep them both (ip-api.com returns valid json after all, there might be no need to alter those strings) or remove them both

**Comment by masonr** [comment]
Just pushed some changes (52f048b) to fix this. Can you give it a test and let me know if it worked? Should leave any instances of `\"` intact.

**Comment by plerohellec** [comment]
I don't know how to test this particular case, I would need a server with an IP address tied to those special ip info strings, which I don't have. But I received a few yabs in the past 10 hours from random IPs, I ran one myself and the generated json is valid.
Thank you for the fix!

**Comment by masonr** [comment]
Right, makes sense. Well please let me know if this comes up again and we'll re-open this issue!

No problem, thanks for the bug report!
