### ISSUE TITLE
Automatically save output to file

### ISSUE THREAD

**Issue by kleutzinger** [masonr/yet-another-bench-script#87]
It would be cool if the output was automatically stored somewhere as a file. Maybe using `tee` to a tempfile of some kind.

Reasoning:
I ran the benchmark over ssh, but then I accidentally disconnected later before I could look over the whole result.

Workaround:
I could have run this instead from the start 
`curl -sL yabs.sh | bash | tee out.log` 

but automatically storing the output seems like a sane default to me. Notifying the user where it is stored seems like a good idea too, like
> `Output stored to /tmp/$date-yabs.log`  

or something

**Comment by masonr** [comment]
I like the idea of adding an option to write the output to a file. I'll have to ask around and maybe conduct a quick poll to see if having the output write to file as a default is wanted by others as well.

**Comment by wolveix** [comment]
I think it would make more sense to either use a flag for this, or just pipe it out (per your example @kleutzinger). Enabling it by default would lead to orphaned files for most users I suspect

**Comment by masonr** [comment]
Closing this one for now. I think the `tee` option is best and doesn't result in orphaned files or needing to add _yet another_ flag/option to the script. Willing to revisit in the future if there's a significant interest.
