### ISSUE TITLE
blank results for disk speed tests on alpine 

### ISSUE THREAD

**Issue by thebigbone** [masonr/yet-another-bench-script#88]
```
fio Disk Speed Tests (Mixed R/W 50/50) (Partition /dev/vda2):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       |                   () |                   ()
Write      |                   () |                   ()
Total      | 0.00 KB/s        (0) | 0.00 KB/s        (0)
           |                      |                     
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       |                   () |                   ()
Write      |                   () |                   ()
Total      | 0.00 KB/s        (0) | 0.00 KB/s        (0)
```
Hello. I tried running yabs on Alpine 3.19. It seems to be skipping the disk test. Any ideas on what could be the issue?

```shell
uname -a
Linux 6.6.31-0-virt #1-Alpine SMP PREEMPT_DYNAMIC Fri, 17 May 2024 12:37:38 +0000 x86_64 GNU/Linux
```

**Comment by masonr** [comment]
@thebigbone sorry for the late response. Usually see this occur when the fio binary doesn't play nice with your OS and I think I've seen this happen on Alpine previously. I recommend installing fio locally first and re-run the script. YABS will detect the locally installed binaries first before downloading the pre-compiled ones from the repo.

**Comment by hugmouse** [comment]
Works if installed `fio` from Alpine's repos.

`apk add fio` and then just rerun the script, should work after that
