### ISSUE TITLE
error: comments in the middle of array

### ISSUE THREAD

**Issue by sedlund** [masonr/yet-another-bench-script#91]
https://github.com/masonr/yet-another-bench-script/blob/a18e1bcd60f5ab9e3640c650726d8949b7bb5bfe/yabs.sh#L808-L817

comments in the middle of an array doesn't work.

**Comment by masonr** [comment]
What kind of errors are you getting? I've never seen this cause any issues to date.

**Comment by sedlund** [comment]
my mistake.  this is ok.

I was having problems running it inside a container where it would not send the json to a server.
