### ISSUE TITLE
Unclear how to specify partition path for fio disk speed test 

### ISSUE THREAD

**Issue by awoz** [masonr/yet-another-bench-script#95]
Please add an option or instructions for speed testing a specific partition. Also clarify if the test is a raw I/O or filesystem test. thx

**Comment by luigi8bits** [comment]
Bro, regarding the specific partition, I included the answer from the developer in another topic:

#6 
The script uses whichever disk you are actively in when you call the script (essentially your pwd). So before you run the script, simply cd into a directory that belongs to the disk that you wish to test.

**Comment by awoz** [comment]
Thanks Bro

**Comment by masonr** [comment]
Thanks bros!

Also, the fio disk speed test uses the direct=1 flag to test direct I/O to the disk rather than buffered.
